///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PostResponseModelDataDataPostsUserRoles {
/*
{
  "id": 3,
  "name": "society_admin"
}
*/

  int? id;
  String? name;

  PostResponseModelDataDataPostsUserRoles({
    this.id,
    this.name,
  });
  PostResponseModelDataDataPostsUserRoles.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class PostResponseModelDataDataPostsUser {
/*
{
  "id": 30,
  "name": "Shalini",
  "society_id": 1,
  "flat_no": "101",
  "mobile_number": "+918979908832",
  "verified": true,
  "roles": [
    {
      "id": 3,
      "name": "society_admin"
    }
  ]
}
*/

  int? id;
  String? name;
  int? societyId;
  String? flatNo;
  String? mobileNumber;
  bool? verified;
  List<PostResponseModelDataDataPostsUserRoles?>? roles;

  PostResponseModelDataDataPostsUser({
    this.id,
    this.name,
    this.societyId,
    this.flatNo,
    this.mobileNumber,
    this.verified,
    this.roles,
  });
  PostResponseModelDataDataPostsUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    societyId = json['society_id']?.toInt();
    flatNo = json['flat_no']?.toString();
    mobileNumber = json['mobile_number']?.toString();
    verified = json['verified'];
    if (json['roles'] != null) {
      final v = json['roles'];
      final arr0 = <PostResponseModelDataDataPostsUserRoles>[];
      v.forEach((v) {
        arr0.add(PostResponseModelDataDataPostsUserRoles.fromJson(v));
      });
      roles = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['society_id'] = societyId;
    data['flat_no'] = flatNo;
    data['mobile_number'] = mobileNumber;
    data['verified'] = verified;
    if (roles != null) {
      final v = roles;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['roles'] = arr0;
    }
    return data;
  }
}

class PostResponseModelDataDataPosts {
/*
{
  "id": 8,
  "title": "vsgsv",
  "content": "gdggdgdggdvdvxvdvdbbdbbdbxbbdvxvvx",
  "likes": 1,
  "admin_notice": 0,
  "created_at": "2023-11-26T14:32:59.000000Z",
  "updated_at": "2023-11-28T14:08:07.000000Z",
  "media": [
    "https://gate.prettybro.com/storage/images/sun101/30/2023-11-26/1701009162.jpg"
  ],
  "user": {
    "id": 30,
    "name": "Shalini",
    "society_id": 1,
    "flat_no": "101",
    "mobile_number": "+918979908832",
    "verified": true,
    "roles": [
      {
        "id": 3,
        "name": "society_admin"
      }
    ]
  }
}
*/

  int? id;
  String? title;
  String? content;
  int? likes;
  int? adminNotice;
  String? createdAt;
  String? updatedAt;
  List<String?>? media;
  PostResponseModelDataDataPostsUser? user;

  PostResponseModelDataDataPosts({
    this.id,
    this.title,
    this.content,
    this.likes,
    this.adminNotice,
    this.createdAt,
    this.updatedAt,
    this.media,
    this.user,
  });
  PostResponseModelDataDataPosts.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    content = json['content']?.toString();
    likes = json['likes']?.toInt();
    adminNotice = json['admin_notice']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    if (json['media'] != null) {
      final v = json['media'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      media = arr0;
    }
    user = (json['user'] != null) ? PostResponseModelDataDataPostsUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['content'] = content;
    data['likes'] = likes;
    data['admin_notice'] = adminNotice;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (media != null) {
      final v = media;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['media'] = arr0;
    }
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}

class PostResponseModelDataData {
/*
{
  "total_records": 14,
  "current_page": 2,
  "posts": [
    {
      "id": 8,
      "title": "vsgsv",
      "content": "gdggdgdggdvdvxvdvdbbdbbdbxbbdvxvvx",
      "likes": 1,
      "admin_notice": 0,
      "created_at": "2023-11-26T14:32:59.000000Z",
      "updated_at": "2023-11-28T14:08:07.000000Z",
      "media": [
        "https://gate.prettybro.com/storage/images/sun101/30/2023-11-26/1701009162.jpg"
      ],
      "user": {
        "id": 30,
        "name": "Shalini",
        "society_id": 1,
        "flat_no": "101",
        "mobile_number": "+918979908832",
        "verified": true,
        "roles": [
          {
            "id": 3,
            "name": "society_admin"
          }
        ]
      }
    }
  ]
}
*/

  int? totalRecords;
  int? currentPage;
  List<PostResponseModelDataDataPosts?>? posts;

  PostResponseModelDataData({
    this.totalRecords,
    this.currentPage,
    this.posts,
  });
  PostResponseModelDataData.fromJson(Map<String, dynamic> json) {
    totalRecords = json['total_records']?.toInt();
    currentPage = json['current_page']?.toInt();
    if (json['posts'] != null) {
      final v = json['posts'];
      final arr0 = <PostResponseModelDataDataPosts>[];
      v.forEach((v) {
        arr0.add(PostResponseModelDataDataPosts.fromJson(v));
      });
      posts = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total_records'] = totalRecords;
    data['current_page'] = currentPage;
    if (posts != null) {
      final v = posts;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['posts'] = arr0;
    }
    return data;
  }
}

class PostResponseModelData {
/*
{
  "message": "Posts listing.",
  "data": {
    "total_records": 14,
    "current_page": 2,
    "posts": [
      {
        "id": 8,
        "title": "vsgsv",
        "content": "gdggdgdggdvdvxvdvdbbdbbdbxbbdvxvvx",
        "likes": 1,
        "admin_notice": 0,
        "created_at": "2023-11-26T14:32:59.000000Z",
        "updated_at": "2023-11-28T14:08:07.000000Z",
        "media": [
          "https://gate.prettybro.com/storage/images/sun101/30/2023-11-26/1701009162.jpg"
        ],
        "user": {
          "id": 30,
          "name": "Shalini",
          "society_id": 1,
          "flat_no": "101",
          "mobile_number": "+918979908832",
          "verified": true,
          "roles": [
            {
              "id": 3,
              "name": "society_admin"
            }
          ]
        }
      }
    ]
  },
  "status_code": 200
}
*/

  String? message;
  PostResponseModelDataData? data;
  int? statusCode;

  PostResponseModelData({
    this.message,
    this.data,
    this.statusCode,
  });
  PostResponseModelData.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    data = (json['data'] != null) ? PostResponseModelDataData.fromJson(json['data']) : null;
    statusCode = json['status_code']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['data'] = this.data!.toJson();
      data['status_code'] = statusCode;
    return data;
  }
}

