///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PostRequestModel {
/*
{
  "title": "Title",
  "content": "THis is content",
  "admin_notice": true,
  "media": [
    "http://127.0.0.1:8000/storage/images/12131sdsd/1/2023-11-19/1700410180.png"
  ]
}
*/

  String? title;
  String? content;
  bool? adminNotice;
  List<String?>? media;

  PostRequestModel({
    this.title,
    this.content,
    this.adminNotice,
    this.media,
  });
  PostRequestModel.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    content = json['content']?.toString();
    adminNotice = json['admin_notice'];
    if (json['media'] != null) {
      final v = json['media'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      media = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['content'] = content;
    data['admin_notice'] = adminNotice;
    if (media != null) {
      final v = media;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['media'] = arr0;
    }
    return data;
  }
}
