///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UploadImageResponseModelData {
/*
{
  "image_path": "https://bubblesapp.s3.us-east-2.amazonaws.com/1642486773.jpg"
}
*/

  String? imagePath;

  UploadImageResponseModelData({
    this.imagePath,
  });

  UploadImageResponseModelData.fromJson(Map<String, dynamic> json) {
    imagePath = json['image_path']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['image_path'] = imagePath;
    return data;
  }
}

class UploadImageResponseModel {
/*
{
  "data": {
    "image_path": "https://bubblesapp.s3.us-east-2.amazonaws.com/1642486773.jpg"
  },
  "message": "Response Successfully!",
  "status_code": 200
}
*/

  UploadImageResponseModelData? data;
  String? message;
  int? statusCode;

  UploadImageResponseModel({
    this.data,
    this.message,
    this.statusCode,
  });

  UploadImageResponseModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? UploadImageResponseModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
    statusCode = json['status_code']?.toInt();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
      data['message'] = message;
    data['status_code'] = statusCode;
    return data;
  }
}
