///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RegisterDetailsRequestModel {


  String? name;
  String? flatNumber;
  String? societyCode;
  String? password;
  String? cnfPassword;

  RegisterDetailsRequestModel({
    this.name,
    this.flatNumber,
    this.societyCode,
    this.password,
    this.cnfPassword
  });
  RegisterDetailsRequestModel.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    flatNumber = json['flat_number']?.toString();
    societyCode = json['society_code']?.toString();
    password = json['password']?.toString();
    cnfPassword = json['cnfPassword']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['flat_number'] = flatNumber;
    data['society_code'] = societyCode;
    data['password'] = password;
    data['cnfPassword'] = cnfPassword;
    return data;
  }
}
