///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CommonResponseModel {
/*
{
  "message": "user already exist",
  "status_code": 200
}
*/

  String? message;
  int? statusCode;

  CommonResponseModel({
    this.message,
    this.statusCode,
  });
  CommonResponseModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    statusCode = json['status_code']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status_code'] = statusCode;
    return data;
  }
}
