import 'dart:convert';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

LocationModel locationModelFromJson(String str) => LocationModel.fromJson(json.decode(str));

String locationModelToJson(LocationModel data) => json.encode(data.toJson());

class LocationModel {
/*
{
  "id": 3,
  "user_id": 3,
  "address_type": 1,
  "city": "repofdfgfghgtrdffhfa",
  "country": "India",
  "formatted_address": "Sector 46, Chandigarh, 160047, India",
  "additional_info": "Sector 46, Chandigarh, 160047, India",
  "latitude": 30.701564345457,
  "longitude": 76.765275656757,
  "primary_address": 1,
  "name": "vxcvbvb",
  "country_code": "+91",
  "postal_code": "",
  "phone_number": "12345679890"
}
*/

  int? id;
  int? userId;
  int? addressType;
  String? city;
  String? country;
  String? formattedAddress;
  String? additionalInfo;
  double? latitude;
  double? longitude;
  int? primaryAddress;
  String? name;
  String? countryCode;
  String? postalCode;
  String? phoneNumber;

  LocationModel({
    this.id,
    this.userId,
    this.addressType,
    this.city,
    this.country,
    this.formattedAddress,
    this.additionalInfo,
    this.latitude,
    this.longitude,
    this.primaryAddress,
    this.name,
    this.countryCode,
    this.postalCode,
    this.phoneNumber,
  });

  LocationModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['user_id']?.toInt();
    addressType = json['address_type']?.toInt();
    city = json['city']?.toString();
    country = json['country']?.toString();
    formattedAddress = json['formatted_address']?.toString();
    additionalInfo = json['additional_info']?.toString();
    latitude = json['latitude']?.toDouble();
    longitude = json['longitude']?.toDouble();
    primaryAddress = json['is_primary']?.toInt();
    name = json['name']?.toString();
    countryCode = json['country_code']?.toString();
    postalCode = json['pincode']?.toString();
    phoneNumber = json['phone_number']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['address_type'] = addressType;
    data['city'] = city;
    data['country'] = country;
    data['formatted_address'] = formattedAddress;
    data['additional_info'] = additionalInfo;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['is_primary'] = primaryAddress;
    data['name'] = name;
    data['country_code'] = countryCode;
    data['pincode'] = postalCode;
    data['phone_number'] = phoneNumber;
    return data;
  }
}
