///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PushNotificationModel {
/*
{
  "title": "hello",
  "order_id": 1,
  "status": 12,
  "body": "Title of Your Notification in Title"
}
*/

  String? title;
  String? userId;
  String? isApproved;
  String? body;

  PushNotificationModel({
    this.title,
    this.userId,
    this.isApproved,
    this.body,
  });
  PushNotificationModel.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    userId = json['user_id']?.toString();
    isApproved = json['is_approved']?.toString();
    body = json['body']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['user_id'] = userId;
    data['is_approved'] = isApproved;
    data['body'] = body;
    return data;
  }
}
