
import 'dart:convert';

AuthResponseModel authResponseModelFromJson(String str) =>
    AuthResponseModel.fromJson(json.decode(str));

String authResponseModelToJson(AuthResponseModel data) => json.encode(data.toJson());



///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
class AuthResponseModelDataUserRoles {
/*
{
  "id": 2,
  "name": "user"
}
*/

  int? id;
  String? name;

  AuthResponseModelDataUserRoles({
    this.id,
    this.name,
  });
  AuthResponseModelDataUserRoles.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class AuthResponseModelDataUser {
/*
{
  "id": 1,
  "name": "Akshay",
  "society_id": 1,
  "flat_no": "135F",
  "mobile_number": "9857473474",
  "verified": true,
  "roles": [
    {
      "id": 2,
      "name": "user"
    }
  ]
}
*/

  int? id;
  String? name;
  int? societyId;
  String? flatNo;
  String? mobileNumber;
  bool? verified;
  List<AuthResponseModelDataUserRoles?>? roles;

  AuthResponseModelDataUser({
    this.id,
    this.name,
    this.societyId,
    this.flatNo,
    this.mobileNumber,
    this.verified,
    this.roles,
  });
  AuthResponseModelDataUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    societyId = json['society_id']?.toInt();
    flatNo = json['flat_no']?.toString();
    mobileNumber = json['mobile_number']?.toString();
    verified = json['verified'];
    if (json['roles'] != null) {
      final v = json['roles'];
      final arr0 = <AuthResponseModelDataUserRoles>[];
      v.forEach((v) {
        arr0.add(AuthResponseModelDataUserRoles.fromJson(v));
      });
      roles = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['society_id'] = societyId;
    data['flat_no'] = flatNo;
    data['mobile_number'] = mobileNumber;
    data['verified'] = verified;
    if (roles != null) {
      final v = roles;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['roles'] = arr0;
    }
    return data;
  }
}

class AuthResponseModelData {
/*
{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiYWY0ZDIxYjkzNjlhYjczNWY5MmQ0NDFkYzBhMTQ2MGViYTI1NDgxZTU1ZmZkMzBjYWExMTk2OGMxYjg2MDZmOWZmNzcwZjBkMWI0MjFhMTciLCJpYXQiOjE2OTgzOTQ4OTguNjEyODM2LCJuYmYiOjE2OTgzOTQ4OTguNjEyODQxLCJleHAiOjE3MzAwMTcyOTguNjEwNTkxLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.L6uFzzkS2h0X8o4pxdD62utt-FnWQpYesY2D8vgG-PH7jBwfVb1uTrOYwCEE42JiEEefWXzGyimlZj3tlxq2zO-dIxnY7k6nTm9IdEmeQI3UWPD7V49uEFWVQZHmCtKSSuDUU2O-4jmpiv_IQYYKOJzOQec21QubCcuTglfU2wykGR0XZyGagiHmJCks5a8oS6PYFowcchGsM3gnSanPM1i9wWrJex-nPrX4DYFQjP26Kdjz_ppoEaGA3ypD3Xfo0lDvupIJSkfCJjWLX3Xb81UkIQPaRdUG7XS359cbSI_RnyAQiQGKS4Ae3Ll5oOep6KP_CXwTjgbeuM89vQJ47qPzcBlpoUC9WAtkiM4gJjRwNOPkqfOErQYap-glAuV2SW5yNmS_H7KkR-F4bGn8QWwicm1Amcq6tE7n_2i87T_-TQ8M6C1lwT1YCgWhLhbgS6kdkCSct0y2YkNX9Lr1MldBaMpvw-nWJrDO_Gxtbz36m4hR8JlfI0o7apAC1nq0r4xvZOuF3lF0tYgXp56ZbLkeZajax4f2wBcEt0TsyOME5G3v_1zRLKNLAKpx5CYI0Lh0TaOLfTlPbc1V0k-9ZuZdkqVSm3fV88RQZTCmyctbS5bEAd3wWfRjisRyjASpfI-gxLRyEPQp0CH5nm8ZMyuF796XmRzEDpf9mk8jwa8",
  "user": {
    "id": 1,
    "name": "Akshay",
    "society_id": 1,
    "flat_no": "135F",
    "mobile_number": "9857473474",
    "verified": true,
    "roles": [
      {
        "id": 2,
        "name": "user"
      }
    ]
  }
}
*/

  String? accessToken;
  AuthResponseModelDataUser? user;

  AuthResponseModelData({
    this.accessToken,
    this.user,
  });
  AuthResponseModelData.fromJson(Map<String, dynamic> json) {
    accessToken = json['access_token']?.toString();
    user = (json['user'] != null) ? AuthResponseModelDataUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['access_token'] = accessToken;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}

class AuthResponseModel {
/*
{
  "message": "Login successful.",
  "data": {
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiYWY0ZDIxYjkzNjlhYjczNWY5MmQ0NDFkYzBhMTQ2MGViYTI1NDgxZTU1ZmZkMzBjYWExMTk2OGMxYjg2MDZmOWZmNzcwZjBkMWI0MjFhMTciLCJpYXQiOjE2OTgzOTQ4OTguNjEyODM2LCJuYmYiOjE2OTgzOTQ4OTguNjEyODQxLCJleHAiOjE3MzAwMTcyOTguNjEwNTkxLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.L6uFzzkS2h0X8o4pxdD62utt-FnWQpYesY2D8vgG-PH7jBwfVb1uTrOYwCEE42JiEEefWXzGyimlZj3tlxq2zO-dIxnY7k6nTm9IdEmeQI3UWPD7V49uEFWVQZHmCtKSSuDUU2O-4jmpiv_IQYYKOJzOQec21QubCcuTglfU2wykGR0XZyGagiHmJCks5a8oS6PYFowcchGsM3gnSanPM1i9wWrJex-nPrX4DYFQjP26Kdjz_ppoEaGA3ypD3Xfo0lDvupIJSkfCJjWLX3Xb81UkIQPaRdUG7XS359cbSI_RnyAQiQGKS4Ae3Ll5oOep6KP_CXwTjgbeuM89vQJ47qPzcBlpoUC9WAtkiM4gJjRwNOPkqfOErQYap-glAuV2SW5yNmS_H7KkR-F4bGn8QWwicm1Amcq6tE7n_2i87T_-TQ8M6C1lwT1YCgWhLhbgS6kdkCSct0y2YkNX9Lr1MldBaMpvw-nWJrDO_Gxtbz36m4hR8JlfI0o7apAC1nq0r4xvZOuF3lF0tYgXp56ZbLkeZajax4f2wBcEt0TsyOME5G3v_1zRLKNLAKpx5CYI0Lh0TaOLfTlPbc1V0k-9ZuZdkqVSm3fV88RQZTCmyctbS5bEAd3wWfRjisRyjASpfI-gxLRyEPQp0CH5nm8ZMyuF796XmRzEDpf9mk8jwa8",
    "user": {
      "id": 1,
      "name": "Akshay",
      "society_id": 1,
      "flat_no": "135F",
      "mobile_number": "9857473474",
      "verified": true,
      "roles": [
        {
          "id": 2,
          "name": "user"
        }
      ]
    }
  }
}
*/

  String? message;
  AuthResponseModelData? data;

  AuthResponseModel({
    this.message,
    this.data,
  });
  AuthResponseModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    data = (json['data'] != null) ? AuthResponseModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['data'] = this.data!.toJson();
      return data;
  }
}
