// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGgDmipEcAsgKEfz67cAjcm8dFZ_PHe30',
    appId: '1:806838503582:web:ca67e555a3af97733ed38f',
    messagingSenderId: '806838503582',
    projectId: 'my-gate-user',
    authDomain: 'my-gate-user.firebaseapp.com',
    storageBucket: 'my-gate-user.appspot.com',
    measurementId: 'G-QSCH67LTTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCPoRtB--BBZhRSzYU4pHCqx6sS5dDXzc',
    appId: '1:806838503582:android:0568b0d8f1895d243ed38f',
    messagingSenderId: '806838503582',
    projectId: 'my-gate-user',
    storageBucket: 'my-gate-user.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCilt7r0BPhXuld8SzQCqf3xnfpbsO7ekA',
    appId: '1:806838503582:ios:0cba5a0242d22b263ed38f',
    messagingSenderId: '806838503582',
    projectId: 'my-gate-user',
    storageBucket: 'my-gate-user.appspot.com',
    iosBundleId: 'com.example.flSevengenSocietyUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCilt7r0BPhXuld8SzQCqf3xnfpbsO7ekA',
    appId: '1:806838503582:ios:79007b9796fd03b13ed38f',
    messagingSenderId: '806838503582',
    projectId: 'my-gate-user',
    storageBucket: 'my-gate-user.appspot.com',
    iosBundleId: 'com.example.flSevengenSocietyUserApp.RunnerTests',
  );
}
